### PR TITLE
index: Use codecs.open instead of open

### PR DESCRIPTION
**Pull request by cpitclaudel**
Is this the fix you had in mind for #13 ?

### CODE REVIEW

**Comment by cpitclaudel** [comment]
It's not clear to me that codecs does indeed read that encoding line. `tokenize.open` seems like a safer choice, but it only works on Python 3.2+

**Comment by birkenfeld** [comment]
codecs doesn't use the encoding line, it just opens in binary mode, the same as using `'rb'` with built-in open. That should suffice, since `ast.parse` can leave decoding to the Python tokenizer/parser.

Apropos Python 3.2+, that would be quite fine. Practically nobody uses 3.0 or 3.1 anymore, or should in fact do so.

**Comment by cpitclaudel** [comment]
Oh, I see :) Should I modify this to just open in binary then?

**Comment by birkenfeld** [comment]
Sure!

**Pull request merged**
